### ISSUE TITLE
Data import seems to have not run yesterday?

### ISSUE THREAD

**Issue by njsmith** [crflynn/pypistats.org#1]
Hello! You probably already know this, but just in case: it looks like the live site doesn't have any data for 7-28, even though we're almost to the end of 7-29.

(Very cool site by the way!)

**Comment by crflynn** [comment]
Thanks for pointing this out. Looks like the instance is running out of memory (running on a t2.micro). I'm guessing the linehaul issue was quite significant, and now with less data loss the google bigquery daily tables are 10-12 GB now. I'll have to upgrade the instance; I'll get it backfilled asap.

**Comment by njsmith** [comment]
The linehaul issue was extremely significant, yeah. I think it'll be a week or two until we know for sure what the new tables look like, since the new linehaul was deployed just before the weekend, which is the low-traffic part of the week... the table for 7-27 is actually 18 GB.

If free-tier resource limits are being an issue, we could ask @ewdurbin and @dstufft about whether it would make sense for pypistats.org to move onto PSF infrastructure. I don't think the PyPI maintainers have spare energy to build or maintain a site like this, but it definitely fills an important need, and it sounds like the needed infrastructure is pretty modest.

**Comment by crflynn** [comment]
In hindsight I should probably be running the ingestion job in a Lambda rather than alongside the server...

I have another 8 months within the AWS free tier. The actual costs would be about $50/month. The aggregate data takes up only about 8 GB so far in a postgres db, so altogether it's pretty lightweight.

If it makes sense to migrate to PSF at some point I would be happy to do so. I haven't touched this project in a while other than to regularly extend the retention time, but if there are any other metrics that might be interesting for you or other developers to see I can add them to my TODOs.

**Comment by levi-rs** [comment]
There are some Issues for these:
https://github.com/pypa/warehouse/issues/699
